### ISSUE TITLE
Define formatting rules with `.clang-format`

### ISSUE THREAD

**Issue by aleasims** [NilFoundation/zkEVM-framework#10]
We should specify our formatting rules and use `clang-format` to check them (also in CI). I suggest basing on Google style with the following custom settings:

```yaml
# Language: Cpp
# BasedOnStyle: Google
AccessModifierOffset: -2
ColumnLimit: 100
IndentWidth: 4
InsertNewlineAtEOF: true
NamespaceIndentation: All
SpaceAfterTemplateKeyword: false
```

To see the full Google style settings use:

```bash
clang-format -style=Google -dump-config > out.yaml
```

[Clang Format Reference](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)

### Comments on custom settings

1. `AccessModifierOffset: -2` - seems a bit easier to differentiate this offset comparing to original `-1`
2. `ColumnLimit: 100` - 80 characters seems a bit obsolete in nowadays
3. `IndentWidth: 4` - again seems a bit easier to differentiate this offset comparing to `2`
4. `InsertNewlineAtEOF: true` - not to forget to keep empty line at the end of files
5. `SpaceAfterTemplateKeyword: false` - I'm not sure why this is in Google style, looks pretty annoying

### Clang Format version

Also there are some complications when using different `clang-format` versions. Some of the options are getting deprecated. So for stability I suggest pinning `clang-format` version for now to `clang-format-17`. That's the latest available version on NixOS Search.

### CI integration

We can use [clang-format Check](https://github.com/marketplace/actions/clang-format-check) to check formatting for our project.
